// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTVqpzoU-L2ygJ2_D9hqfU1xZFJ82Va8',
    appId: '1:345095751202:web:77e94f66b4778e7cf7ec7b',
    messagingSenderId: '345095751202',
    projectId: 'expense-tracker-app-868ab',
    authDomain: 'expense-tracker-app-868ab.firebaseapp.com',
    storageBucket: 'expense-tracker-app-868ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5PgRAmHXCkHV25mmYhXgYPt3GPMNKxhk',
    appId: '1:345095751202:android:9d4dd8ada6462c3ff7ec7b',
    messagingSenderId: '345095751202',
    projectId: 'expense-tracker-app-868ab',
    storageBucket: 'expense-tracker-app-868ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0I8VWF6wiU02AJxKYZMbRKL7MNXzoXI0',
    appId: '1:345095751202:ios:a210f2356c37785ff7ec7b',
    messagingSenderId: '345095751202',
    projectId: 'expense-tracker-app-868ab',
    storageBucket: 'expense-tracker-app-868ab.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0I8VWF6wiU02AJxKYZMbRKL7MNXzoXI0',
    appId: '1:345095751202:ios:a210f2356c37785ff7ec7b',
    messagingSenderId: '345095751202',
    projectId: 'expense-tracker-app-868ab',
    storageBucket: 'expense-tracker-app-868ab.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTVqpzoU-L2ygJ2_D9hqfU1xZFJ82Va8',
    appId: '1:345095751202:web:b3e40326f95a43a5f7ec7b',
    messagingSenderId: '345095751202',
    projectId: 'expense-tracker-app-868ab',
    authDomain: 'expense-tracker-app-868ab.firebaseapp.com',
    storageBucket: 'expense-tracker-app-868ab.firebasestorage.app',
  );
}
